# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.8

font_size 12
disable_ligatures always
# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' style=Regular features='+zero'
bold_font        family='JetBrains Mono' style=Bold features='+zero'
italic_font      family='JetBrains Mono' style=Italic features='+zero'
bold_italic_font family='JetBrains Mono' style='Bold Italic' features='+zero'
# END_KITTY_FONTS

# only for jet brains
modify_font underline_thickness 75%

remember_window_size  no
initial_window_width  1000
initial_window_height 600

# tmux specifics
clipboard_control write-primary write-clipboard no-append

# mac specifics
map alt+w no_op
map cmd+w no_op

# performance

# increase this if flickering in fullscreen
input_delay 10
repaint_delay 2
sync_to_monitor yes
wayland_enable_ime no

enable_audio_bell no

tab_bar_style hidden

# fix mouse flickering
mouse_hide_wait 3.0 0.05 5 yes
